[build-system]
requires = [
    "setuptools>=61",
]
build-backend = "setuptools.build_meta"

[project]
name = "ammico"
version = "0.2.1"
description = "AI Media and Misinformation Content Analysis Tool"
readme = "README.md"
maintainers = [
    { name = "Inga Ulusoy", email = "ssc@iwr.uni-heidelberg.de" },
    { name = "Petr Andriushchenko", email = "ssc@iwr.uni-heidelberg.de" },
]
requires-python = ">=3.8"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]

dependencies = [
    "bertopic<=0.14.1",
    "dash>=2.11.0",
    "datasets",
    "deepface<=0.0.93",
    "googletrans==4.0.0rc1",
    "google-cloud-vision",
    "grpcio",
    "importlib_metadata",
    "importlib_resources",
    "ipython",
    "jupyter_dash",
    "matplotlib",
    "numpy<=2.1.1",
    "pandas",
    "Pillow",
    "pooch",
    "protobuf",
    "pytest",
    "pytest-cov",
    "Requests",
    "retina_face",
    "ammico-lavis>=1.0.2.3",
    "setuptools",
    "spacy<=3.7.5",
    "tensorflow>=2.13.0",
    "tf-keras",
    "torch<2.4.0",
    "transformers",
    "google-cloud-vision",
    "dash_bootstrap_components",
    "colorgram.py",
    "webcolors>1.13",
    "colour-science",
    "scikit-learn>1.3.0",
    "tqdm"
]

[project.scripts]
ammico_prefetch_models = "ammico.utils:ammico_prefetch_models"

[project.urls]
homepage = "https://github.com/ssciwr/AMMICO"  # FIXME not shown by pip
documentation = "https://ssciwr.github.io/AMMICO/build/html/index.html"

[tool.setuptools]
packages = ["ammico","ammico.data"]

[tool.setuptools.package-data]
# Include any png and csv files found in the "data" subdirectory of "ammico"
"ammico.data" = ["*.png", "*.csv"]

