[build-system]
requires = [
    "setuptools==61",
]
build-backend = "setuptools.build_meta"

[project]
name = "misinformation"
version = "0.0.1"
description = "Misinformation campaign analysis"
readme = "README.md"
maintainers = [
    { name = "Inga Ulusoy", email = "ssc@iwr.uni-heidelberg.de" },
    { name = "Dominic Kempf", email = "ssc@iwr.uni-heidelberg.de" },
]
requires-python = ">=3.9"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "google-cloud-vision",
    "cvlib",
    "deepface",
    "ipywidgets",
    "numpy",
    "opencv_python",
    "pandas",
    "pooch",
    "protobuf",
    "retina_face",
    "setuptools",
    "tensorflow",
    "keras",
    "openpyxl",
    "pytest",
    "pytest-cov",
    "matplotlib",
    "pytest",
    "opencv-contrib-python",
    "googletrans-3.1.0a0",
]

[project.scripts]
misinformation_prefetch_models = "misinformation.utils:misinformation_prefetch_models"

[tool.setuptools]
packages = ["misinformation"]
