[build-system]
requires = [
    "setuptools==61",
]
build-backend = "setuptools.build_meta"

[project]
name = "misinformation"
version = "0.0.1"
description = "Misinformation campaign analysis"
readme = "README.md"
maintainers = [
    { name = "Inga Ulusoy", email = "ssc@iwr.uni-heidelberg.de" },
    { name = "Dominic Kempf", email = "ssc@iwr.uni-heidelberg.de" },
    { name = "Petr Andriushchenko", email = "ssc@iwr.uni-heidelberg.de" },
]
requires-python = ">=3.8"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "bertopic",
    "cvlib",
    "deepface<=0.0.75",
    "googletrans==3.1.0a0",
    "grpcio",
    "importlib_metadata",
    "ipython",
    "ipywidgets<8.0.5",
    "matplotlib",
    "numpy<=1.23.4",
    "pandas",
    "Pillow",
    "pooch",
    "protobuf",
    "pytest",
    "pytest-cov",
    "requests",
    "retina_face @ git+https://github.com/iulusoy/retinaface.git",
    "salesforce-lavis @ git+https://github.com/iulusoy/LAVIS.git",
    "spacy",
    "spacytextblob",
    "tensorflow",
    "textblob",
    "torch",
    "google-cloud-vision",
    "setuptools",
    "opencv-contrib-python",
]

[project.scripts]
misinformation_prefetch_models = "misinformation.utils:misinformation_prefetch_models"

[tool.setuptools]
packages = ["misinformation"]
