name: CI
  

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
  
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        # os: [ubuntu-22.04,windows-latest,macos-latest]
        python-version: [3.9]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
    # - name: Run pytest test_colors
      # run: |
        # cd ammico
        # python -m pytest test/test_colors.py -svv --cov=. --cov-report=xml --cov-append
    # - name: Run pytest test_cropposts
      # run: |
        # cd ammico
        # python -m pytest test/test_cropposts.py -svv --cov=. --cov-report=xml --cov-append
    # - name: Run pytest test_display
    #   run: |
    #     cd ammico
    #     python -m pytest test/test_display.py -svv --cov=. --cov-report=xml --cov-append
    # - name: Run pytest test_faces
    #   run: |
    #     cd ammico
    #     python -m pytest test/test_faces.py -svv --cov=. --cov-report=xml --cov-append
    # - name: Run pytest test_multimodal_search
    #   run: |
    #     cd ammico
    #     python -m pytest test/test_multimodal_search.py -m "not long" -svv --cov=. --cov-report=xml --cov-append
    - name: Run pytest test_objects
      run: |
        cd ammico
        python -m pytest test/test_objects.py -sxvv --cov=. --cov-report=xml --cov-append
    # - name: Run pytest test_summary
    #   run: |
    #     cd ammico
    #     python -m pytest test/test_summary.py -m "not long" -svv --cov=. --cov-report=xml --cov-append
    # - name: Clear cache
    #   if: matrix.os == 'ubuntu-22.04'
    #   run: |
    #       rm -rf ~/.cache/*
    # - name: Run pytest test_text
    #   run: |
    #     cd ammico
    #     python -m pytest test/test_text.py -m "not gcv" -svv --cov=. --cov-report=xml --cov-append
    # - name: Run pytest test_utils
    #   run: |
    #     cd ammico
    #     python -m pytest test/test_utils.py -svv --cov=. --cov-report=xml --cov-append
    # - name: Upload coverage
    #   if: matrix.os == 'ubuntu-22.04' && matrix.python-version == '3.9'
    #   uses: codecov/codecov-action@v3
    #   with:
    #     fail_ci_if_error: true
    #     files: ammico/coverage.xml
    #     verbose: true
    #     token: ${{ secrets.CODECOV_TOKEN }}
